### ISSUE TITLE
bug when loading certain documents using PdfViewer.uri()

### ISSUE THREAD

**Issue by potatothesparky** [espresso3389/pdfrx#11]
I get the following error when loading some test pdf files from uri.

```
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (index): Invalid value: Valid value range is empty: 0
#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      PdfDocumentPdfium.getPage (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:271:58)
#2      _PdfViewerState._onDocumentChanged (package:pdfrx/src/pdfrx_widgets.dart:363:24)
#3      PdfDocumentRef.notifyListeners (package:pdfrx/src/pdfrx_widgets.dart:53:15)
#4      PdfDocumentStore.load.<anonymous closure> (package:pdfrx/src/pdfrx_widgets.dart:108:14)
<asynchronous suspension>
#5      objectSynchronized.<anonymous closure> (package:synchronized/src/extension_impl.dart:37:18)
<asynchronous suspension>
#6      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#7      objectSynchronized (package:synchronized/src/extension_impl.dart:34:12)
<asynchronous suspension>
[ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: RangeError (end): Invalid value: Not in inclusive range 262144..393532: 655676
#0      RangeError.checkValidRange (dart:core/errors.dart:365:9)
#1      _TypedListBase.setRange (dart:typed_data-patch/typed_data_patch.dart:109:18)
#2      _IntListMixin.setRange (dart:typed_data-patch/typed_data_patch.dart)
#3      PdfFileCacheMemory.read (package:pdfrx/src/pdfrx_downloader.dart:104:12)
#4      pdfDocumentFromUri.<anonymous closure> (package:pdfrx/src/pdfrx_downloader.dart:198:21)
<asynchronous suspension>
```

code to reproduce:

```
import 'package:flutter/material.dart';
import 'package:pdfrx/pdfrx.dart';

class HomeScreen extends StatelessWidget {
  const HomeScreen({super.key});

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(title: Text('Home')),
      body: Center(
        child: PdfViewer.uri(
          Uri.parse(
              'https://upload.wikimedia.org/wikipedia/commons/3/31/LEVEL_11_FLOOR_PLAN.pdf'),
        ),
      ),
    );
  }
}
```

the same pdf loads without error if dowloaded to assets and displayed using PdfViewer.asset()

the problem was present on android and ios. Web didn't display the pdf but didn't throw the error.

**Comment by espresso3389** [comment]
[0.3.3](https://pub.dev/packages/pdfrx/versions/0.3.3) fixes the issue.

The cause of the issue is that small PDF file are cached immediately on memory/file and handled differently from larger files. And the small file cache logic is just broken :(

**Comment by potatothesparky** [comment]
Thanks for the speedy update. that seems to have fixed the problem i was having.
