### ISSUE TITLE
Range error when scrolling pdf

### ISSUE THREAD

**Issue by thecodepapaya** [espresso3389/pdfrx#141]
Getting the below error repeatedly when scrolling a pdf file on Android.

```
I/flutter (21743): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21743): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21743): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (21743): #1      _PdfPageTextOverlayState._initText (package:pdfrx/src/widgets/pdf_page_text_overlay.dart:72:34)
I/flutter (21743): <asynchronous suspension>
I/flutter (21743): ----------------------------------------------------
I/flutter (21743): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21743): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21743): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (21743): #1      _PdfPageTextOverlayState._initText (package:pdfrx/src/widgets/pdf_page_text_overlay.dart:72:34)
I/flutter (21743): <asynchronous suspension>
I/flutter (21743): ----------------------------------------------------
I/flutter (21743): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21743): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21743): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (21743): #1      _PdfPageTextOverlayState._initText (package:pdfrx/src/widgets/pdf_page_text_overlay.dart:72:34)
I/flutter (21743): <asynchronous suspension>
I/flutter (21743): ----------------------------------------------------
I/flutter (21743): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21743): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21743): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (21743): #1      _PdfPageTextOverlayState._initText (package:pdfrx/src/widgets/pdf_page_text_overlay.dart:72:34)
I/flutter (21743): <asynchronous suspension>
I/flutter (21743): ----------------------------------------------------
I/flutter (21743): ----------------FIREBASE CRASHLYTICS----------------
I/flutter (21743): RangeError (index): Invalid value: Valid value range is empty: 0
I/flutter (21743): #0      List.[] (dart:core-patch/growable_array.dart:264:36)
I/flutter (21743): #1      _PdfPageTextOverlayState._initText (package:pdfrx/src/widgets/pdf_page_text_overlay.dart:72:34)
```

**Comment by espresso3389** [comment]
Which version are you using?
