### ISSUE TITLE
RangeError on PdfViewer.uri when missing "Expires" header

### ISSUE THREAD

**Issue by czaefferer** [espresso3389/pdfrx#206]
When using `PdfViewer.uri` with a Uri that does not return an "Expires" header, the viewer crashes with this:

```
RangeError (index): Invalid value: Only valid value is 0: 1

#0      List.[] (dart:core-patch/growable_array.dart:264:36)
#1      _parseHttpDateTime (package:pdfrx/src/http_cache_control.dart:224:30)
#2      HttpCacheControlState.fromHeaders (package:pdfrx/src/http_cache_control.dart:104:21)
#3      _downloadBlock (package:pdfrx/src/pdf_file_cache.dart:521:29)
<asynchronous suspension>
#4      pdfDocumentFromUri (package:pdfrx/src/pdf_file_cache.dart:383:24)
<asynchronous suspension>
#5      PdfDocumentListenable.load.<anonymous closure> (package:pdfrx/src/pdf_document_ref.dart:401:22)
<asynchronous suspension>
#6      objectSynchronized.<anonymous closure> (package:synchronized/src/extension_impl.dart:37:18)
<asynchronous suspension>
#7      BasicLock.synchronized (package:synchronized/src/basic_lock.dart:33:16)
<asynchronous suspension>
#8      objectSynchronized (package:synchronized/src/extension_impl.dart:34:12)
<asynchronous suspension>
#9      PdfDocumentListenable.load (package:pdfrx/src/pdf_document_ref.dart:395:12)
<asynchronous suspension>
```

I am currently using json-server as a mock web-service to get data from like this:

```javascript
if(req.path.startsWith('/pdf/')) {
    var file = fs.createReadStream('./example.pdf');
    var stat = fs.statSync('./example.pdf');
    res.setHeader('Content-Length', stat.size);
    res.setHeader('Content-Type', 'application/pdf');
    // res.setHeader('expires', 'Wed, 21 Oct 2015 07:28:00 GMT');
    res.setHeader('Content-Disposition', 'attachment; filename=example.pdf');
    file.pipe(res);
    return;
}
```

For now I can fix this by adding the "Expires" header, however the real server will also not send this header later on (environment is Linux).

**Comment by espresso3389** [comment]
1.0.79 contain the fix.
