### ISSUE TITLE
 Invalid argument(s): Failed to load dynamic library 'pdfrx.framework/pdfrx'

### ISSUE THREAD

**Issue by pierlucatonioloreply** [espresso3389/pdfrx#212]
Hi, when I try to use pdfrx to open a pdf  on iOS (real device and simulator) I have a blue screen with this error:

Invalid argument(s): Failed to load dynamic library 'pdfrx.framework/pdfrx': dlopen(pdfrx.framework/pdfrx, 0x0001): tried: 'pdfrx.framework/pdfrx' (no such file), '/private/preboot/Cryptexes/OSpdfrx.framework/pdfrx' (no such file), '/usr/lib/swift/pdfrx.framework/pdfrx' (no such file, not in dyld cache), '/private/preboot/Cryptexes/OS/usr/lib/swift/pdfrx.framework/pdfrx' (no such file), '/private/var/containers/Bundle/Application/1E7BCA5E-33B9-4AC7-83A9-9723BDC25A5C/Runner.app/Frameworks/pdfrx.framework/pdfrx' (no such file), '/usr/lib/pdfrx.framework/pdfrx' (no such file, not in dyld cache), 'pdfrx.framework/pdfrx' (no such file), '/System/Library/Frameworks/pdfrx.framework/pdfrx' (no such file, not in dyld cache)

#0      _open (dart:ffi-patch/ffi_dynamic_library_patch.dart:11:43)
#1      new DynamicLibrary.open (dart:ffi-patch/ffi_dynamic_library_patch.dart:22:12)
#2      pdfium (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:31:43)
#3      pdfium (package:pdfrx/src/pdfium/pdfrx_pdfium.dart)
#4      _init.<anonymous closure> (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:46:7
.....

I have no problems with Android and I can see the pdf correctly.

Doctor summary (to see all details, run flutter doctor -v):
[!] Flutter (Channel stable, 3.19.6, on macOS 14.5 23F79 darwin-arm64, locale en-IT)
    ! Warning: `dart` on your path resolves to /opt/homebrew/Cellar/dart/3.4.3/libexec/bin/dart, which is not inside your current Flutter SDK checkout at /Users/pierlucatoniolo/FlutterSdk/flutter. Consider adding /Users/pierlucatoniolo/FlutterSdk/flutter/bin to
      the front of your path.
[✓] Android toolchain - develop for Android devices (Android SDK version 33.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 15.2)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2024.1)
[✓] IntelliJ IDEA Community Edition (version 2023.1)
[✓] VS Code (version 1.89.1)
[✓] Connected device (4 available)            
[✓] Network resources

! Doctor found issues in 1 category.

iOS 17.5.1

I have tried to clean and rebuild the project, from both xcode and flutter clean. I have tried to manually delete the build folder. I have tried to manually add the pdfrx.framework under "Framework, Libraries, and Embedded Content" in the general tab of the Runner target.

Thanks in advice for more suggestions

**Comment by espresso3389** [comment]
Could you please also delete .pub_cache folder?

**Comment by pierlucatonioloreply** [comment]
Deleted the .pub_cache folder in my $HOME but I have the same error.
<img width="404" alt="image" src="https://github.com/user-attachments/assets/17d3caeb-f075-4c66-999e-9877629cdae1">

**Comment by espresso3389** [comment]
At least, the following folders are generated during the build:
- `${workspaceRoot}/build`
- `${workspaceRoot}/ios/.symlinks`
- `${workspaceRoot}/ios/Pods`
- `~/.pub_cache`

I'm not sure what triggers your issue, please remove all of them and try again.

**Comment by espresso3389** [comment]
Ah, could you please check the existence of the following file?

```
${workspaceRoot}/build/ios/Debug-iphoneos/Runner.app/Frameworks/pdfrx.framework/pdfrx
```

`Debug-iphoneos` may be different for each build config anyway.

**Comment by tologonkudaiberdiuulu** [comment]
same issue for me (

**Comment by espresso3389** [comment]
@pierlucatonioloreply @tologonkudaiberdiuulu Could you please check the existence of the file above? Does it exist?

**Comment by tologonkudaiberdiuulu** [comment]
@espresso3389 I just made cleaned with flutter clean. And while installing pods.
<img width="347" alt="image" src="https://github.com/user-attachments/assets/0a54a3e9-071c-429d-b865-8affeb9c8062">

Just hanged out like this. Not finishing installing

**Comment by tologonkudaiberdiuulu** [comment]
I got error @espresso3389 

<img width="809" alt="image" src="https://github.com/user-attachments/assets/3ca7a74b-9b10-45f1-ba4b-705c166e2fde">

**Comment by tologonkudaiberdiuulu** [comment]
Finally it's installed. But when trying to build getting error again @espresso3389 

<img width="611" alt="image" src="https://github.com/user-attachments/assets/cf234623-1d00-4381-96c5-4da3ae7495b4">

**Comment by tologonkudaiberdiuulu** [comment]
> Could you please check the existence of the file above? Does it exist?

I couldn't find

**Comment by pierlucatonioloreply** [comment]
> @pierlucatonioloreply @tologonkudaiberdiuulu Could you please check the existence of the file above? Does it exist?

I have the file 
![image](https://github.com/user-attachments/assets/78b9344d-e6af-4d4f-a1ed-99a054476c51)

**Comment by pierlucatonioloreply** [comment]
> @espresso3389 I just made cleaned with flutter clean. And while installing pods. <img alt="image" width="347" src="https://private-user-images.githubusercontent.com/47391827/350354398-0a54a3e9-071c-429d-b865-8affeb9c8062.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjEzODQ5NjksIm5iZiI6MTcyMTM4NDY2OSwicGF0aCI6Ii80NzM5MTgyNy8zNTAzNTQzOTgtMGE1NGEzZTktMDcxYy00MjlkLWI4NjUtOGFmZmViOWM4MDYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzE5VDEwMjQyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRkYzc1MWE4YTUwOTRjMTRlZjAwMjRlMmQzZTI0Y2U1Y2UwMWM2ZTM0ZWVkNTZlZTI0ZDBiOGMzY2ViYTBlODgmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2ZJUiBIBl5_Oym9gTPwsAS9JkYGtjf6uDKMrJKek3tU">
> 
> Just hanged out like this. Not finishing installing

It took me a moment but it installed without errors. The blue screen with the error remains the same when I try to open the PDF

**Comment by espresso3389** [comment]
@tologonkudaiberdiuulu

On your case,  downloading of the pdfium-ios.tgz failed.

So, please fix your network environment to properly download the files.

Or, please manually download the [files](https://github.com/espresso3389/pdfrx/releases/tag/pdfium-apple-v9) and place them on `pdfium/.lib/pdfium-apple-v9` and retry the build.

**Comment by pierlucatonioloreply** [comment]
> At least, the following folders are generated during the build:
> 
> * `${workspaceRoot}/build`
> * `${workspaceRoot}/ios/.symlinks`
> * `${workspaceRoot}/ios/Pods`
> * `~/.pub_cache`
> 
> I'm not sure what triggers your issue, please remove all of them and try again.

I have tried it multiple times. Full clean of all autogenerated folders, cleaning the project from xcode -> product -> clean build folder, flutter clean, updating/reinstalling with pod install, deleting pubspec.lock and podfile.lock. I also tried to manually add the pdfrx.framework here in the "Build Phases" of the runner target in xcode (I don't remember which folder I took the reference to pdfrx from)
![image](https://github.com/user-attachments/assets/055edbcd-ee6a-413a-8570-640106715173)

**Comment by espresso3389** [comment]
@pierlucatonioloreply 
I have completely no idea what's happenning on your env. What plugins do you use with your app?

**Comment by pierlucatonioloreply** [comment]
> @pierlucatonioloreply I have completely no idea what's happenning on your env. What plugins do you use with your app?

this is the list. Last action that I have done is -> flutter pub upgrade --major-versions. I have done this to upgrade from pdf_renderer to the last version of pdfrx. 

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  flutter_command: ^5.0.0+17
  get_it_mixin: ^4.2.2
  get_it: ^7.2.0
  flutter_triple: ^1.2.4+3
  json_annotation: ^4.1.0
  flutter_secure_storage: ^9.2.2
  visibility_detector: ^0.4.0+2
  #flutter_cached_pdfview: ^0.4.2
  cupertino_icons: ^1.0.2
  retrofit: any
  logger: ^2.4.0
  flutter_dotenv: ^5.0.2
  local_auth: ^2.1.6
  intl: ^0.17.0
  flutter_html: ^3.0.0-alpha.2
  webview_flutter: ^3.0.0
  url_launcher: ^6.0.18
  file_picker: ^8.0.5
  pdfrx: ^1.0.82
  google_maps_flutter: ^2.1.1
  charts_flutter_new: ^0.12.0
  decimal: ^2.1.0
  flutter_svg: ^2.0.10+1
  flutter_screenutil: ^5.3.1
  flutter_slidable: ^3.0.1
  image_picker: ^1.1.2
  share_plus: ^9.0.0
  flutter_polyline_points: ^2.1.0
  photo_view: ^0.15.0
  uuid: ^4.4.2
  device_info_plus: ^10.1.0
  package_info_plus: ^8.0.0
  secure_application: ^4.0.1
  flutter_exif_rotation: ^0.5.0
  html_unescape: ^2.0.0
  pull_to_refresh: ^2.0.0
  shared_preferences: ^2.0.13
  time_machine: ^0.9.17
  firebase_core: ^3.2.0
  firebase_analytics: ^11.2.0
  firebase_performance: ^0.10.0+3
  firebase_crashlytics: ^4.0.3
  dotted_border: ^2.0.0+3
  dio: ^5.0.0
  upgrader: ^10.3.0
  dropdown_button2: ^2.1.3
  cached_network_image: ^3.2.3
  path_provider: ^2.1.0
  geocoding: ^3.0.0
  maps_launcher: ^2.2.0
  geolocator: ^12.0.0
  intl_phone_number_input: ^0.7.2
  timezone: ^0.9.2
  flutter_cache_manager: ^3.3.1
  pinput: ^2.3.0
  provider: ^6.1.1

**Comment by espresso3389** [comment]
Wow, it's too many... My guess is that some of the other plugins interferes the build of pdfrx. Basic strategy is that:

1. Create a new empty app
2. Add pfdrx and add the basic code to load some PDF (possiblly asset is a better choise)
3. Add the plugins one by one and run the app

So could you do that?

**Comment by espresso3389** [comment]
Oh, before doing such bruteforce check, we should check the actual ipa file.

**Comment by espresso3389** [comment]
On [the screenshot](https://github.com/espresso3389/pdfrx/issues/212#issuecomment-2237010308), the critical issue here is:

```
'/Users/pierlucatoniolo/Library/Developer/CoreSimulator/Devices/D6817B61-ADO8-4F1E-9599-D9EB9A4B5827/data/Containers/Bundle/Application/FA7AC6AD-F3BC-434C-A1DA-45128C16208D/Runner.app/Frameworks/pdfrx.framework/pdfrx' (no such file)
```

It means your Runner.app does not contain pdfrx binary there. It means some build process removes the binary or framework. Something in your Podfile may remove the binary...

Did you modify your Podfile to do something special?

**Comment by espresso3389** [comment]
Mmm, no... I "believe" that `build/ios/Debug-iphonesimulator/Runner.app` should be identical to the actual ipa file installed on the device. But pdfrx binary seems to exist there...

**Comment by espresso3389** [comment]
https://github.com/espresso3389/pdfrx/issues/212#issuecomment-2238930639 says "not found". Sometimes error is "could not be loaded" or such if dependencies are missing or anyway the file is broken. The file apparently does not exist. What's happening on archiving or installing...

**Comment by espresso3389** [comment]
Oh, we also need to clear Pod cache (`~/Library/Caches/CocoaPods`). How is it?

**Comment by pierlucatonioloreply** [comment]
One comment to reply all:
 - I haven't modified the podfile and I haven't done anything special
 - Yes I think I can try to add a new dependency each time in a new project, I'll keep it as a final test if everything else doesn't work
 - Now I have tried clearing the ~/Library/Caches/CocoaPods but the error is still there
 
I have tried starting again from my branch with pdf_render.
1) Upgrade all to --major-versions except 3 packages whose update introduces too many errors -> with pdf_render I can see the pdfs.
2) Add pdfrx and use file() instead of openFile() -> I see the error instead of the pdf.

maybe I should try with a new project to see if is another package that cause this issue, as you suggested before.

**Comment by eugeneyjy** [comment]
Try doing this inside your project root folder. I face the same problem and doing these commands fix the problem for me.
```
pod cache clean --all
rm -rf ~/Library/Caches/CocoaPods
rm -rf ios/Pods
```
