### ISSUE TITLE
Can we get thumbnails(from bookmarks) using controller's isReady property?

### ISSUE THREAD

**Issue by Zhanerkeb** [espresso3389/pdfrx#53]
without controller.isReady thumbnail view gives an error null check used on null value
however with isReady thumbnail view just shows blank tab

**Comment by espresso3389** [comment]
Could you give me more info about your error? Actual error, stacktrace, `flutter doctor`, and so on.

**Comment by Zhanerkeb** [comment]
<img width="536" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/d35e9a4a-68ca-438f-ab6c-80d90e52adae">
<img width="370" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/016434d6-187e-43fa-8781-8987db1d6fa4">

**Comment by Zhanerkeb** [comment]
• Upstream repository https://github.com/flutter/flutter.git
    • Framework revision 78666c8dc5 (6 weeks ago), 2023-12-19 16:14:14 -0800
    • Engine revision 3f3e560236
    • Dart version 3.2.3
    • DevTools version 2.28.4
    • If those were intentional, you can disregard the above warnings; however it is recommended to use "git"
      directly to perform update checks and upgrades.

[✓] Android toolchain - develop for Android devices (Android SDK version 32.1.0-rc1)
    • Android SDK at /Users/zhanerke/Library/Android/sdk
    • Platform android-33, build-tools 32.1.0-rc1
    • Java binary at: /Applications/Android Studio.app/Contents/jre/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 15.0)
    • Xcode at /Applications/Xcode.app/Contents/Developer
    • Build 15A240d
    • CocoaPods version 1.14.2

[✓] Chrome - develop for the web
    • Chrome at /Applications/Google Chrome.app/Contents/MacOS/Google Chrome

[✓] Android Studio (version 2021.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/9212-flutter
    • Dart plugin can be installed from:
      🔨 https://plugins.jetbrains.com/plugin/6351-dart
    • Java version OpenJDK Runtime Environment (build 11.0.11+0-b60-7772763)

[✓] VS Code (version 1.85.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension can be installed from:
      🔨 https://marketplace.visualstudio.com/items?itemName=Dart-Code.flutter

**Comment by espresso3389** [comment]
Could you please enable "All Exceptions" and check what code causes the actual issue.

![image](https://github.com/espresso3389/pdfrx/assets/1311400/a6cefddb-2c87-4b01-8a3c-06823b5ca5aa)

**Comment by Zhanerkeb** [comment]
<img width="953" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/aa944957-4623-4a50-ad0c-75f6bc126ece">

**Comment by Zhanerkeb** [comment]
<img width="662" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/5e807c57-e4a9-4c0c-b1e8-db1e6fe61478">

**Comment by espresso3389** [comment]
Oh, the following code change may fix the issue:

```dart
child: controller?.isReady != true || controller?.documentRef == null
  ? null
  : PdfDocumentViewBuilder(
```

**Comment by espresso3389** [comment]
Wow, so the fix above leads to the problem shown in the title. OK. I understood...

**Comment by espresso3389** [comment]
[0.4.30](https://pub.dev/packages/pdfrx/versions/0.4.30) (557456a) is released. And it contains fix for the example.

The most important part of the example change is that it uses a new ValueNotifier and ThumbnailsView is updated by ValueListenableBuilder:

https://github.com/espresso3389/pdfrx/blob/557456a8fe33253e3c06c74330aac4fe28767ca0/example/lib/main.dart#L34

**Comment by Zhanerkeb** [comment]
> [0.4.30](https://pub.dev/packages/pdfrx/versions/0.4.30) ([557456a](https://github.com/espresso3389/pdfrx/commit/557456a8fe33253e3c06c74330aac4fe28767ca0)) is released. And it contains fix for the example.
> 
> The most important part of the example change is that it uses a new ValueNotifier and ThumbnailsView is updated by ValueListenableBuilder:
> 
> https://github.com/espresso3389/pdfrx/blob/557456a8fe33253e3c06c74330aac4fe28767ca0/example/lib/main.dart#L34

Should I use also onViewerReady, because I couldn't get PDF Page views in thumbnails tab

**Comment by espresso3389** [comment]
Oh, I didn't introduce onViewerReady on the issue. Yes, please use onViewerReady for your purpose.

**Comment by Zhanerkeb** [comment]
I need to resolve issue with Cmake, onViewerReady is in 32's version:(

**Comment by Zhanerkeb** [comment]
<img width="353" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/c9cecaf0-f283-466d-a7dc-67061e278047">
No error, however thumbnails are not shown:(((
I have added onViewerReady
I forked repo and added 3.18.1 to build.gradle

**Comment by espresso3389** [comment]
Do you run the example code? Or any other code?

**Comment by espresso3389** [comment]
Your screenshot does not seem to the example code (because outline/search tabs are missing).
If so, you should show me your code. I don't know anything about your code.

**Comment by Zhanerkeb** [comment]
I want to get only thumbnails

**Comment by espresso3389** [comment]
So please show your codes. Do you wrap your ThumbnailView with ValueListenableBuilder correctly?

https://github.com/espresso3389/pdfrx/blob/52de2dae0e16bac8666b8ac979510ea21f6b4b2e/example/lib/main.dart#L125-L129

**Comment by espresso3389** [comment]
Mmm, the example code is not correct :(

**Comment by espresso3389** [comment]
[0.4.37](https://pub.dev/packages/pdfrx/versions/0.4.37) contains the following "example" fixes:

- [humbnails_view.dart](https://github.com/espresso3389/pdfrx/blob/755e65ff3c19d776619f73060dca6728d60d7fb5/example/lib/thumbnails_view.dart)
- main.dart
https://github.com/espresso3389/pdfrx/blob/755e65ff3c19d776619f73060dca6728d60d7fb5/example/lib/main.dart#L127-L134

**Comment by espresso3389** [comment]
There are two important points on the previous example's problem (and why it works)

- Drawer ensures that ThumbnailsView is generated later than PdfViewer's document load
- Example Bug (but example code itself is not affected by the bug): ThumbnailsView is a child of ValueListenableBuilder and it is generated regardless of ValueListenableBuilder's state change
  - We should move it to ValueListenableBuilder's builder

So the causes your problem is that you've removed drawer code.
And If ThumbnailView is directly placed without drawer, it should be moved to ValueListenableBuilder's builder because child does not affected by ValueListenableBuilder state updates.

**Comment by Zhanerkeb** [comment]
`Row(
              children: [
                AnimatedSize(
                  duration: const Duration(milliseconds: 300),
                  child: ValueListenableBuilder(
                    valueListenable: showLeftPane,
                    builder: (context, showLeftPane, child) => SizedBox(
                      width: showLeftPane ? 300 : 0,
                      child: child!,
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(1, 0, 4, 0),
                      child: DefaultTabController(
                        length: 1,
                        child: Column(
                          children: [
                            const TabBar(tabs: [
                              Tab(text: 'Thumbnails'),
                            ]),
                            Expanded(
                              child: TabBarView(
                                children: [
                                  ValueListenableBuilder(
                                    valueListenable: documentRef,
                                    builder: (context, documentRef, child) =>
                                        ThumbnailsView(
                                      documentRef: documentRef,
                                      controller: pdfController,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ),
                ),
                Expanded(child: 
                Stack(children: [
 PdfViewer.file(
            _path,

            controller: pdfController,

            passwordProvider: () => passwordDialog(context, themeData),
            params: PdfViewerParams(
              pageAnchor: PdfPageAnchor.all,
              backgroundColor: themeData.primaryColor,
              errorBannerBuilder:
                  (context, error, stackTrace, documentRef) => Center(
                child: Text(
                  error.toString(),
                ),
              ),
              onDocumentChanged: (document) async {
                if (document == null) {
                  documentRef.value = null;
                }
              },
              onViewerReady: (document, controller) async {
                documentRef.value = controller.documentRef;
              },
              viewerOverlayBuilder: (context, size) => [
                PdfViewerScrollThumb(
                  controller: pdfController,
                  orientation: ScrollbarOrientation.right,
                  thumbSize: const Size(40, 25),
                  thumbBuilder:
                      (context, thumbSize, pageNumber, controller) =>
                          Container(
                    color: Colors.black,
                    child: Center(
                      child: Text(
                        pageNumber.toString(),
                        style: const TextStyle(color: Colors.white),
                      ),
                    ),
                  ),
                ),
              ],
            ),
          ),

  ])
                )
              ],
            )`

**Comment by Zhanerkeb** [comment]
My code like your example code, except this
`DefaultTabController(
                        length: 1,
                        child: Column(
                          children: [
                            const TabBar(tabs: [
                              Tab(text: 'Thumbnails'),
                            ]),
                            Expanded(
                              child: TabBarView(
                                children: [
                                  ValueListenableBuilder(
                                    valueListenable: documentRef,
                                    builder: (context, documentRef, child) =>
                                        ThumbnailsView(
                                      documentRef: documentRef,
                                      controller: pdfController,
                                    ),
                                  ),
                                ],
                              ),
                            ),
                          ],
                        ),
                      ),`

**Comment by Zhanerkeb** [comment]
Thumbnail code is like an example code.
Below the main code.
```dart
Row(
          children: [
                AnimatedSize(
                  duration: const Duration(milliseconds: 300),
                  child: ValueListenableBuilder(
                    valueListenable: showLeftPane,
                    builder: (context, showLeftPane, child) => SizedBox(
                      width: showLeftPane ? 300 : 0,
                      child: child!,
                    ),
                    child: Padding(
                      padding: const EdgeInsets.fromLTRB(1, 0, 4, 0),
                      child: Expanded(
                        child:  ValueListenableBuilder(
                          valueListenable: documentRef,
                          builder: (context, documentRef, child) =>
                              ThumbnailsView(
                                documentRef: documentRef,
                                controller: pdfController,
                              ),
                        ),
                      )
                    ),
                  ),
                ),
                Expanded(child: pdfViewer())
              ],
            )

**Comment by Zhanerkeb** [comment]
Now with your updated code, it gives esrror:
```dart
 PdfException: FPDFBitmap_CreateEx(0, 0) failed.
E/flutter (30356): #0      PdfPagePdfium.render.<anonymous closure>.<anonymous closure>.<anonymous closure> (package:pdfrx/src/pdfium/pdfrx_pdfium.dart:551:21)
E/flutter (30356): #1      _ComputeParams.execute (package:pdfrx/src/pdfium/worker.dart:55:43)
E/flutter (30356): #2      BackgroundWorker._workerEntry.<anonymous closure> (package:pdfrx/src/pdfium/worker.dart:28:17)
E/flutter (30356): #3      _RootZone.runUnaryGuarded (dart:async/zone.dart:1594:10)
E/flutter (30356): #4      _BufferingStreamSubscription._sendData (dart:async/stream_impl.dart:339:11)
E/flutter (30356): #5      _BufferingStreamSubscription._add (dart:async/stream_impl.dart:271:7)
E/flutter (30356): #6      _SyncStreamControllerDispatch._sendData (dart:async/stream_controller.dart:784:19)
E/flutter (30356): #7      _StreamController._add (dart:async/stream_controller.dart:658:7)
E/flutter (30356): #8      _StreamController.add (dart:async/stream_controller.dart:606:5)
E/flutter (30356): #9      _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184:12)

**Comment by Zhanerkeb** [comment]
<img width="343" alt="image" src="https://github.com/espresso3389/pdfrx/assets/55015545/f0c27b7e-aefc-4277-8a63-476c3ec8e2a5">

**Comment by espresso3389** [comment]
The reason of `PdfException: FPDFBitmap_CreateEx(0, 0) failed` is that your builder always emit `child!` even if the leftPage size is 0.

**Comment by espresso3389** [comment]
What I mean is;

```dart
builder: (context, showLeftPane, child) => SizedBox(
  width: showLeftPane ? 300 : 0,
  child: showLeftPane ? child! : null,
),
```

**Comment by Zhanerkeb** [comment]
Oh, it works now

**Comment by Zhanerkeb** [comment]
thank you!)
